<?xml version="1.0"?>
<package format="3">
  <name>drone_system_pkg</name>
  <version>0.1.0</version>
  <description>PX4-oriented bird deterrence simulation (MAVROS-style topics)</description>

  <maintainer email="ysun1@seattleu.edu">Yi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>mavros_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>